<?php

/**
 * Implement hook_field_info().
 */
function demo_field_field_info() {
  return array(
    'demo_field' => array(
      'label' => t('Demo field'),
      'description' => t('Field API demo.'),
    ),
  );
}

/**
 * Create a field. Fields can be created without any needs to attach them to
 * entities.
 */
function demo_field_enable() {
  $field = array(
    'field_name' => 'demo_field',
    'type' => 'text',
  );
  print "Create field\n";
  field_create_field($field);

  /**
   * Bind field to a entity bundle.
   */
  $instance = array(
    'field_name' => 'demo_field',
    'entity_type' => 'node',
    'bundle' => 'article',
    'required' => TRUE,
  );

  field_create_instance($instance);

}
